### ISSUE TITLE
Discovery produces SocketException on broadcastaddress 0.0.0.1 (network unreachable)

### ISSUE THREAD

**Issue by witmoca** [witmoca/BEATs#122]
Sending failed to ip adress /0.0.0.1 on interface /10.0.0.6
java.net.SocketException: Network is unreachable: Datagram send failed
	at java.net.DualStackPlainDatagramSocketImpl.socketSend(Native Method)
	at java.net.DualStackPlainDatagramSocketImpl.send(Unknown Source)
	at java.net.DatagramSocket.send(Unknown Source)
	at be.witmoca.BEATs.discovery.DiscoveryServer.sendBroadcast(DiscoveryServer.java:218)
	at be.witmoca.BEATs.discovery.DiscoveryServer.access$000(DiscoveryServer.java:51)
	at be.witmoca.BEATs.discovery.DiscoveryServer$1.run(DiscoveryServer.java:251)
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)

**Comment by witmoca** [comment]
Suggest auto skipping such errors

**Comment by witmoca** [comment]
Maybe a good time to implement network card selection for the discovery protocol?
Suggest checkboxes instead of radiobuttons to leave the option for multiple NIC's
